name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coding-guidelines:
    name: Coding Guidelines
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: |
        npm ci

    - name: Lint with ESLint
      run: |
        npx eslint .

    - name: Format with Prettier
      run: |
        npx prettier --check .
